Repository ScottBrenner/generate-changelog-action, pull requests merged in 2021-04, with the labels that each got.

#26 feat: adds custom tags values to generate changelog
  README.md
  action.yml
  entrypoint.sh
Labels: enhancement

#28 fix(ci): Restore Docker Image CI test job functionality
  entrypoint.sh
Labels: bug, enhancement

#27 feat: Add support for CLI options
  README.md
  action.yml
  entrypoint.sh
Labels: documentation, enhancement

#29 docs: update README
  README.md
  release.png
Labels: documentation, enhancement
